version: '3.5'
services:
#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
#    container_name: elasticsearch
#    volumes:
#      - esdata:/usr/share/elasticsearch/data
#    ports:
#      - 9300:9300
#      - 9200:9200
#  kibana:
#    image: docker.elastic.co/kibana/kibana:7.7.0
#    container_name: kibana
#    environment:
#     - ELASTICSEARCH_URL="http://elasticsearch:9300"
#    ports:
#      - 5601:5601
#  logstash:
#    image: docker.elastic.co/logstash/logstash:7.7.0
#    container_name: logstash
#    command: logstash -f /etc/logstash/conf.d/logstash.conf
#    volumes:
#      - ./config:/etc/logstash/conf.d.
#    ports:
#      - "5000:5000"
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
#    depends_on:
#      - elasticsearch
#    environment:
#      - "STORAGE_TYPE=elasticsearch"
#      - "ES_HOSTS=elasticsearch:9300"
#      - "JAVA_OPTS=-Xms1G -Xmx1G -XX:+ExitOnOutOfMemoryError"
    ports:
      - "9411:9411"
networks:
  bank:
    driver: bridge



