version: '3.5'
services:
  mysql-transaction:
    image: mysql:8.0.27
    environment:
      - MYSQL_ROOT_PASSWORD=root_pwd
      - MYSQL_DATABASE=transaction_db
      - MYSQL_USER=db-admin
      - MYSQL_PASSWORD=pa55wordingp
    cap_add:
      - SYS_NICE
    ports:
      - "3308:3306"
    volumes:
      - ./data_transaction:/var/lib/mysql
    networks:
      - bank

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - mysql-transaction
    environment:
      PMA_HOST: mysql-transaction
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root_pwd
    ports:
      - 8002:80

networks:
  bank:
    driver: bridge
