keycloak:
  enabled: true
  resource: account
  realm: bank
  auth-server-url: http://localhost:8081/auth

#  HTLbmJI5bHKGsMDjEMKVkJsXm3MmnOUa
server:
  port: 9000
spring:
  main:
     allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}
          jwk-set-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/certs
  datasource:
    url: jdbc:mysql://localhost:3306/account_db
    username: account_us
    password: account_pw
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
cors:
  allowedAdresses: http://localhost:8080, http://localhost:8081
  
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

eureka:
  client:
    registry-fetch-interval-seconds: 15
    fetch-registry: true
    register-with-eureka: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://eurekaUser:eurekaPassword@localhost:8761/eureka
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    preferIpAddress: true

feign:
  hystrix:
    enabled: true
  circuitbreaker:
    enabled: true
hystrix:
  shareSecurityContext: true

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    org.springframework.web: DEBUG