server:
  port: 8283

spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
             allowed-origins: "*"
             allowed-methods: "*"
             allowed-headers: "*"
      routes:
        - id: transaction
          uri: lb://TRANSACTION-SERVICE
          predicates:
            - Path=/transaction/**
          filters:
            - RewritePath=/transaction/(?<path>.*), /$\{path}
        - id: account
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/account/**
          filters:
            - RewritePath=/account/(?<path>.*), /$\{path}
            - name: CircuitBreaker
              args:
                name: account
            - name: Retry
              args:
                retries: 3
                method: GET
                backoff:
                  firstBackoff: 50ms
                  maxBackoff: 500ms
        - id: reporting
          uri: lb://Reporting-Service
          predicates:
            - Path=/reporting/**
          filters:
            - RewritePath=/reporting/(?<path>.*), /$\{path}
            - name: Retry
              args:
                retries: 3
                method: GET
                backoff:
                  firstBackoff: 50ms
                  maxBackoff: 500ms
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://eurekaUser:eurekaPassword@localhost:8761/eureka
  instance:
    preferIpAddress: true

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: gateway
    gateway:
      enabled: true
  info:
    env:
      enabled: true


info:
  application:
    name: '@project.name@'
    version: '@project.version@'
logging:
  level: 
    '[com.netflix.eureka]': DEBUG
    '[com.netflix.discovery]': DEBUG
    '[com.netflix.discovery.shared.resolver.aws]': DEBUG
    org.springframework.web: DEBUG
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

resilience4j:
  circuitbreaker:
    instances:
      account:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        registerHealthIndicator: true
  timelimiter:
    instances:
      bookService:
        timeoutDuration: 3s