server:
  port: 9090
spring:
  main:
     allow-bean-definition-overriding: true

cors:
  allowedAdresses: http://localhost:8080, http://localhost:8081
  
management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

eureka:
  client:
    registry-fetch-interval-seconds: 15
    fetch-registry: true
    register-with-eureka: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://eurekaUser:eurekaPassword@localhost:8761/eureka
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    preferIpAddress: true
